TARGET = arduino

SRC = wiring.c
SRC += WInterrupts.c
SRC += wiring_analog.c
SRC += wiring_digital.c
SRC += wiring_pulse.c
SRC += wiring_shift.c
SRC += hooks.c
SRC += twi.c


###########################################

include $(AVERSIVE_DIR)/mk/aversive_module.mk
